-- EXCEPT RETURNS UNIQUE ROWS FROM THE FIRST QUERY (LEFT SIDE) AND REMOVE DUPLICATES
(
 	SELECT *
    FROM products
    ORDER BY price DESC
    LIMIT 4
)
EXCEPT
(
  SELECT *
  FROM products
  ORDER BY price / weight DESC
  LIMIT 4
)

-- EXCEPT RETURNS UNIQUE ROWS FROM THE FIRST QUERY (LEFT SIDE)
(
 	SELECT *
    FROM products
    ORDER BY price DESC
    LIMIT 4
)
EXCEPT ALL
(
  SELECT *
  FROM products
  ORDER BY price / weight DESC
  LIMIT 4
)