SELECT ('true'::BOOLEAN);
SELECT ('t'::BOOLEAN);
SELECT ('yes'::BOOLEAN);
SELECT ('y'::BOOLEAN);
SELECT ('on'::BOOLEAN);
SELECT (1::BOOLEAN);

SELECT ('false'::BOOLEAN);
SELECT ('f'::BOOLEAN);
SELECT ('no'::BOOLEAN);
SELECT ('n'::BOOLEAN);
SELECT ('off'::BOOLEAN);
SELECT (0::BOOLEAN);

SELECT (null::BOOLEAN);
